### ISSUE TITLE
Support derivation into compound type targets (e.g. mixin traits)

### ISSUE THREAD

**Issue by an-tex** [scalalandio/chimney#126]
Derivation fails when the target contains a mixed in trait:

```scala
import io.scalaland.chimney.dsl._

trait B {
  val b : Int
}

case class A(a : Boolean)

A(true)
  .into[A with B]
  .withFieldConst(_.b, 1)
  .transform
```

results in `Chimney can't derive transformation ...`

**Comment by krzemin** [comment]
This case is not yet supported.

Chimney would have to generate following code in order to support target compound types:

```scala
val src = A(true)
new A(src.a) with B { val b = 1 }
```

Leaving it as feature request for future versions.

**Comment by MateuszKubuszok** [comment]
I'm fairly certain that this feature case would open up a can of worms: we would have to analyze the code to check which fields were instantiated in `A` that where not instantiated in `B` if there is an overlap, handle cases like

```scala
trait X {
  val a: Any 
}
trait Y extends X {
  val a: String
}
trait Z extends X {
  val a: Int
}
class A(val a: Double)

sth.into[A with Y with Z]....transform // what type is a? String & Int?
```

so that we would at least report why it cannot be created. And in general somehow make the behavior intuitive and predictive (which IMHO for many types that have `with` in their definition is difficult to achieve even when we write them explicitly).

I think that since 0.8.4 an acceptable compromise is using `withConstructor` for creating such values:

```scala
import io.scalaland.chimney.dsl._

trait B {
  val b : Int
}

case class A(a : Boolean)

A(true)
  .into[A with B]
  .withConstructor { (a: Double, b: Int) =>
    val b1 = b
    new A(a) with B { val b = 1 }
   }
  .withFieldConst(_.b, 1)
  .transform
```

which would explicitly show how such potentially ambiguous types should be created.
