### ISSUE TITLE
Automatic filling of Unit parameters

### ISSUE THREAD

**Issue by Krever** [scalalandio/chimney#138]
It would be good if parameters of type `Unit` would be automatically filled in, as there is exactly one value of this type. 

Rationale: 
```
case class DbEntry[Id](id: Id, name: String)
type NewEntry = DbEntry[Unit]

case class NewEntryRequest(name: String)

import io.scalaland.chimney.dsl._
(_: NewEntryRequest).into[NewEntry].transform
```

**Comment by krzemin** [comment]
Why not extend it for any singleton type?

**Comment by Krever** [comment]
You mean literal-based singleton types (in 2.13) or (companion) object types or generally stuff like `value.type` ? It probably makes sense, I just don't use them that much and haven't thought of it.  But is there a reliable method of distinguishing singleton types?  https://www.scala-lang.org/api/current/scala/Singleton.html ?

**Comment by krzemin** [comment]
Ok, technically speaking `Unit` is not singleton type from the Scala's type system perspective, despite it contains only single inhabitant. You're right to say that singleton types are not frequently used to model data types, so maybe there's no need to complicate library's code in order to fully support them.

But adding support for auto-filling target fields `f: Unit` with `f = ()` seems to be fine. 2 questions remains:
- do we need opt-out from this behavior (by `.disableAutoFillUnits`)?
- or maybe it should be turned off by default and require explicit opt-in (by `.enableAutoFillUnits`)?

**Comment by Krever** [comment]
So what other ways of filling in such type would there be? You can't even use `null` as `Unit` is an `AnyVal`. The only alternative to `()` would be to throw an exception, which hardly makes any sens to me in transformer logic.

The only close-to-real danger I can imagine is to have unspotted fields of this type, coming out of some type-level shenanigans. But even if this case, chimney would just "not be a barrier" for those fields, but still won't be doing anything incorrect. 

So my vote goes definitely for "enabled by default". If opt-out is not a lot of work it could be added, but I'd rather wait for someone to request it, as I cant imagine a probable use-case for it.

**Comment by ldrygala** [comment]
Hi, I would like to give it a try.

**Comment by Krever** [comment]
Awesome, thank you @ldrygala  :)
