### ISSUE TITLE
Unable to compile when transforming Option[Seq[T] to Seq[T]

### ISSUE THREAD

**Issue by allantl** [scalalandio/chimney#158]
Consider the following example:

```scala
 object Test {

  implicit def optionSeqToSeq[T, U](implicit tf: Transformer[T, U]): Transformer[Option[Seq[T]], Seq[U]] =
    new Transformer[Option[Seq[T]], Seq[U]] {
      override def transform(src: Option[Seq[T]]) = {
        src.getOrElse(Seq.empty).map(_.transformInto[U])
      }
    }

  case class ClassA(a: Option[Seq[String]])
  case class ClassB(a: Seq[String])

  def transform(a: ClassA): ClassB = {
    a.transformInto[ClassB]
  }
}
```

This results in a compilation error
```scala
[error] scala.collection.Seq
[error]   derivation from classa.a: scala.Option to scala.collection.Seq is not supported in Chimney!
```

If I provide an explicit
```scala
implicit val strToStrTransformer: Transformer[String, String] = Transformer.derive
```
Then, chimney would be able to resolve the issue. 
It would be nice if chimney can derive the required implicit automatically.

Context: I need this for proto3 conversion. I have a legacy case class that has a lot of `Option[Seq[T]]`. Since, proto only supports `Seq[T]`, I need to transform `Option[Seq[T]]` to `Seq[T]`.

**Comment by ulanzetz** [comment]
@allantl you can't define optionSeqToSeq, but you can use marco-level defined transformation, using enableOptCollectionFlatting, watch my PR

**Comment by allantl** [comment]
@ulanzetz Oh wow, that was quick 👍

**Comment by krzemin** [comment]
I digged deeper into that issue. It seems that what's happening when chimney tries to generate transformer between `ClassA` and `ClassB` is:
1. It finds pair of fields that matches by name: `a: Option[Seq[String]]` in ClassA,  `a: Seq[String]` in ClassB
2. Before trying to recursively generate transformer, it performs implicit lookup searching for implicit instance of `Transformer[Option[Seq[String]], Seq[String]]`
3. `implicit def optionSeqToSeq[T, U](implicit tf: Transformer[T, U]): Transformer[Option[Seq[T]], Seq[U]]` is considered as a candidate, but for some reason it's rejected
4. Chimney tries to recursively derive transformation, but none of the rules is able to to it
5. Compilation fails with aforementioned error message.

Following common sense, we would expect that in step 3 an implicit rule `optionSeqToSeq` will be chosen as transformer for `a` fields. But this is not an implicit `Transformer` instance per se. It's a rule that is only available only when it's given all the required implicit parameters. In this case it requires `implicit tf: Transformer[T, U]`, where `T = U = String`. Do we have an implicit instance for `Transformer[String, String]`? Well, yes - if we define it explicitly. Otherwise, `Transformer.derive` is able to derive it, but that's implicit macro.

Implicit search in step 2 works with [disabled macro instances](https://github.com/scalalandio/chimney/blob/master/chimney/src/main/scala/io/scalaland/chimney/internal/macros/TransformerMacros.scala#L694), so during implicit instance resolution it's unable to derive `Transformer[String, String]` that is needed for `optionSeqToSeq` to be picked.

This issue affects the whole class of implicit transformers derivation rules that users expect to work, but it's not due to disabling implicit macros. On the other hand, we can't just simply turn it on, as it will cause serious ambiguities on derivation in usual cases.

**Comment by ghostdogpr** [comment]
Having similar issues with conversion between `Seq[T]` and `Chain[T]`:
```scala
implicit def seqToChainTransformer[A, B](implicit ev: Transformer[A, B]): Transformer[Seq[A], Chain[B]] =
  Chain.fromSeq(_).map(ev.transform)
```
This only derives well when I add an explicit Transformer from A to B in scope.

Is there any other workaround? Maybe for this specific case, adding built-in support for `Chain` in the cats module?
