### ISSUE TITLE
Control over default configurations of transformers

### ISSUE THREAD

**Issue by d12frosted** [scalalandio/chimney#176]
Hello,

I have a use case where I want chimney by default not to support default values of case classes and make this feature opt-in, instead of opt-out. I see that in the way chimney currently [generates][1] (derives) transformers it's impossible to do as it simply reuses defaults.

Are there any plans on supporting changing the defaults? 

Thanks in advance.

  [1]: https://github.com/scalalandio/chimney/blob/e9aa7a15df84028ee5df69ab0dd9a7fe2d3fd6f7/chimney/src/main/scala/io/scalaland/chimney/internal/macros/ChimneyBlackboxMacros.scala#L43

**Comment by krzemin** [comment]
It's true that currently there's no possibility to have a global configuration of flags. They are now set in stone and can be changed only one-way using DSL's `enableXXX`/`disableXXX`.

However that should be quite easy to implement such a flexibility. That would require following steps:
- separate configuration flags from field values/providers
- introduce some type that holds configuration and DSL that allows its manipulation; in the companion object there should be a default implicit instance, but user can define own default in the implicit scope
- `.into` and `.derive` will need to take the implicit configuration object and respect its settings
- `Transformer*Into` dsl needs to allow changing flags in both ways (in order to override defaults in the call site, whatever they are)

That would enable opt-in default values and much more.

**Comment by d12frosted** [comment]
Thank you for such a detailed response. I was thinking about similar solution. 

Just for the sake of 'completeness', I think [ConfigDsl][1] should also support changing each flag in both ways.

Now a pragmatic question - is someone willing to implement this in near future? 😸 If no, I could take it.

  [1]: https://github.com/scalalandio/chimney/blob/master/chimney/src/main/scala/io/scalaland/chimney/dsl/ConfigDsl.scala

**Comment by krzemin** [comment]
@d12frosted Feel free to take it 👍

**Comment by nilskp** [comment]
I'd like to add my 2 cents here. I've just spent a couple of days debugging a strange error that ultimately turned out to be a transformation of an `Option` being silently turned the default value of a non-`Option`.

As a general approach, I think it's unfortunate that the default behavior is something other than super strict. I'm now left wondering if I have other bugs waiting to happen.

I think it would be advisable to reconsider the default behavior before 1.0 is released, whenever that'll happen.

**Comment by nilskp** [comment]
I went ahead and disabled default values in a bunch of places, and I got some unexpected errors. So I understand the benefit of using default values *WHEN* there are no name clashes. In my case, the fields had the same name, and were of the same conceptual type (except for the `Option` part of course).

I still think it would be preferable with `enableDefaultValues`, but if not, perhaps only allow default values for field names that have no equivalent name?

**Comment by krzemin** [comment]
> I think it would be advisable to reconsider the default behavior before 1.0 is released, whenever that'll happen.

@nilskp totally agree 👍 together with other breaking changes

> perhaps only allow default values for field names that have no equivalent name?

I suggest to open another issue and provide some motivating example. Maybe worth to consider that too.
