### ISSUE TITLE
Protobuf import doesn't deal with Empty case

### ISSUE THREAD

**Issue by ghostdogpr** [scalalandio/chimney#425]
**Checklist**
- [x] I read the documentation at https://chimney.readthedocs.io/ and checked that the functionality exists
- [x] I verified that the behavior for my use case doesn't match the documentation
- [x] I checked the https://github.com/scalalandio/chimney/issues and haven't found the issue reported
- [x] I confirmed that the bug is not related to functionality that was deprecated: lifted transformers (`TransformerF`s) or `unsafeOption` flags

**Describe the bug**
Apologies if I misunderstood something in the docs.

In the `oneof` part of the docs (https://chimney.readthedocs.io/en/stable/cookbook/#oneof-fields), it says we can handle `Empty` manually like this:
```scala
.withCoproductInstancePartial[pb.addressbook.AddressBookType.Value.Empty.type](
  _ => partial.Result.fromEmpty
)
```
Or using a simple import:
```scala
import io.scalaland.chimney.protobufs._ // includes support for empty scalapb.GeneratedMessage
```
While the first one works well, the second doesn't.

It looks like the import provides `partialTransformerFromEmptyOneOfInstance` for a `GeneratedOneof` with `ValueType = Nothing`, but the protobuf generated code doesn't look like that. It's just a simple `case object Empty`.

**Reproduction**
An easy way to reproduce is to modify the existing unit test `ProtobufOneOfSpec`.

Before:
```scala
pbStatus
  .intoPartial[order.CustomerStatus]
  .withCoproductInstancePartial[pb.order.CustomerStatus.Empty.type](_ => partial.Result.fromEmpty)
  .withCoproductInstance[pb.order.CustomerStatus.NonEmpty](_.transformInto[order.CustomerStatus])
  .transform
  .asOption ==> Some(domainStatus)
```
After:
```scala
import io.scalaland.chimney.protobufs.*
pbStatus
 .intoPartial[order.CustomerStatus]
//  .withCoproductInstancePartial[pb.order.CustomerStatus.Empty.type](_ => partial.Result.fromEmpty)
  .withCoproductInstance[pb.order.CustomerStatus.NonEmpty](_.transformInto[order.CustomerStatus])
  .transform
  .asOption ==> Some(domainStatus)
```

**Expected behavior**
According to the docs, it should compile.

**Actual behavior**
```
[error]    |      pbStatus
[error]    |      ^
[error]    |Chimney can't derive transformation from io.scalaland.chimney.examples.pb.order.CustomerStatus to io.scalaland.chimney.fixtures.order.CustomerStatus
[error]    |
[error]    |io.scalaland.chimney.fixtures.order.CustomerStatus
[error]    |  derivation from empty: io.scalaland.chimney.examples.pb.order.CustomerStatus.Empty to io.scalaland.chimney.fixtures.order.CustomerStatus is not supported in Chimney!
[error]    |
[error]    |
[error]    |io.scalaland.chimney.fixtures.order.CustomerStatus
[error]    |  can't transform coproduct instance io.scalaland.chimney.examples.pb.order.CustomerStatus.Empty to io.scalaland.chimney.fixtures.order.CustomerStatus
```

**Which Chimney version do you use**
0.8.0

**Which platform do you use**
- [x] JVM
- [ ] Scala.js
- [ ] Scala Native

**If you checked JVM**
17

**Additional context**
Looking at the generated code from scalapb, `Empty` is defined like this:
```scala
case object Empty extends io.scalaland.chimney.examples.pb.order.CustomerStatus
```

There is also another `Empty` which is used internally:
```scala
  sealed trait SealedValue extends _root_.scalapb.GeneratedOneof {
    ...
  }
  object SealedValue {
    @SerialVersionUID(0L)
    case object Empty extends io.scalaland.chimney.examples.pb.order.CustomerStatusMessage.SealedValue {
      type ValueType = _root_.scala.Nothing
```
But it's not the one used when we convert types with Chimney so the import doesn't help.

**Comment by MateuszKubuszok** [comment]
Since your `Empty` extends `SealedValue` it is rather clear to me that your case is described here: https://chimney.readthedocs.io/en/stable/cookbook/#sealed_value-oneof-fields.

ScalaPB can generate oneOf in 3 different ways:

 - the default one uses non-flat ADT with `scalapb.GeneratedOneof { type ValueType = Nothing }` for empty value, and we can use this common subtype to handle this `Empty` case - it's the case you are quoting and which is handled by the implicit
 - `sealed_value` which creates extra `Empty` subtype with nothing that we could use to distinguish it from any other `Empty` `case object` which perhaps shouldn't be automatically mapped to a failed transformation - this is the case you have, and you have to handle it manually, sorry
 - `sealed_value_optional` - since ScalaPB does not use nulls, all fields are non-nullable, and empty value has to be represented somehow, the former 2 approaches do this by adding extra empty subtype to ADT, and this one uses `Option` in every place that this oneOf would be used - this one is handled by `PartialTransformer`s and their automatic unwrapping of `Option`s.

So no, it is not a bug. Your protobuf definition explicitly opted-in with the only representation of 3 possible, that Chimney cannot automatically handle and it is decribed in the documentation. You can map things manually or, if you have the ability, change `sealed_value` name in your protobufs to `sealed_value_optional`.

**Comment by ghostdogpr** [comment]
Thanks for the detailed explanation! I wrongly assumed the import was relevant to the second case. This is all clear now 🙏

**Comment by MateuszKubuszok** [comment]
NP, I can add some warning to the docs to make it clearer.
