### ISSUE TITLE
Support for custom strategy of patching via options

### ISSUE THREAD

**Issue by kubukoz** [scalalandio/chimney#64]
EDIT: The actual description is in @krzemin's post below. This was originally a different issue.

Given
```scala
case class Foo(name: String, age: Int)
case class FooPatch(name: Option[String], age: Option[Int])
```

there could be a function taking instances of both and modifying the `Foo` with the present fields from `FooPatch`.

**Comment by krzemin** [comment]
Currently optional fields are supported, but when the optional field in patch is non-empty, it takes precedence over existing field. As I understand, this proposal is to customize behavior to be able to combine final value from the two existing.

We need to find good api for this. I'd like to keep existing behavior default and allow to override by providing the function.

Because existing `patchWith` performs patching in place, we don't really have a space to provide a function to patcher. But following the same convention as we have for transformers (having `transformInto` vs `into[T].transform` in case we need to provide something extra), we could have `with[P].patch`-like syntax.

Then the example code that utilizes the generalized patching feature could look like: 

```
foo
  .with(fooPath)
  .combine(_.name, (old: String, new: String) => old + new)
  .combine(_.age, (old: Int, new: Int) => Math.max(old, new))
  .patch
```

I think this combining mechanism could equally work for both optional and non-optional fields.

**Comment by kubukoz** [comment]
Actually, I was asking about the functionality that you said already exists :P it seems to be left out of the documentation, that's why I had to ask. But providing a custom way for selecting the value to use sounds neat.

**Comment by krzemin** [comment]
Yes, we're missing that in docs. I created #65 then.
