### ISSUE TITLE
Better Java standard libraries interop

### ISSUE THREAD

**Issue by krzemin** [scalalandio/chimney#86]
As we now support Java beans, it might be useful to support automatic transformations between:

- scala `Option` and java `Optional`
- scala collections and java collections
- scala maps and java maps
- java enums and scala sealed families of case objects

anything else?

**Comment by MateuszKubuszok** [comment]
I think that Java enums would have to be added in the macros (ideally [here](https://github.com/scalalandio/chimney/blob/master/chimney-macro-commons/src/main/scala/io/scalaland/chimney/internal/compiletime/datatypes/SealedHierarchies.scala#L12) since it should be similar to `sealed` extended by `val`), but:

* Java's `Optional` concersions: to-from `Option`, into Optional, from Optional, between `Optional`s
* Java's collections conversions: to-from Scala ones, in-between

could be implemented as a separate module e.g. `javatypes`, with implicits. It would not have the same level of support as Scala's collections (no inlining, etc) but it could be acceptable for a feature that not that many people would need and which could add a lot of maintenance burden otherwise (parsing types for Java, handling them on JVM but not on JS and Native, etc).

Adding a new module with implicits and a set of tests would be some work, but it wouldn't be complicated work.
